apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: mywebserver
      labels:
        app: myapp
    spec:
      containers:
        - name: mywebserver
          image: aamirs/radical-private-repo:v1.0
          command: [ "/usr/sbin/httpd", "-D", "FOREGROUND"]
          imagePullPolicy: Always
      imagePullSecrets:
        - name: my-docker-hub-secret
  
  selector:
    matchLabels:
      app: myapp
