apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: mywebserver
      labels:
        app: myapp
    spec:
      containers:
        - name: mywebserver
          image: 587893864223.dkr.ecr.us-east-2.amazonaws.com/radical:1.1.0
  selector:
    matchLabels:
      app: myapp
