apiVersion: v1
kind: Pod
metadata:
  name: apache1
  labels:
    app: myapp
spec:
  containers:
    - name: mywebserver
      image: aamirs/radical-nov-2022:1.0
      command: [ "/usr/sbin/httpd", "-D", "FOREGROUND" ]

    - name: mycentos
      image: centos
      command: ["/bin/sleep", "3650d"]





