apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicatset
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: mywebsite
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: myapp
